version: '3.8'

services:
  web:
    build:
      context: .
      args:
        - MYSQLHOST=${MYSQLHOST}
        - MYSQLPORT=${MYSQLPORT}
        - MYSQLUSER=${MYSQLUSER}
        - MYSQLPASSWORD=${MYSQLPASSWORD}
        - MYSQLDATABASE=${MYSQLDATABASE}
        - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8080:80"
    environment:
      - MYSQLHOST=${MYSQLHOST}
      - MYSQLPORT=${MYSQLPORT}
      - MYSQLUSER=${MYSQLUSER}
      - MYSQLPASSWORD=${MYSQLPASSWORD}
      - MYSQLDATABASE=${MYSQLDATABASE}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${MYSQLDATABASE}
      - MYSQL_USER=${MYSQLUSER}
      - MYSQL_PASSWORD=${MYSQLPASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQLPASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 